[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"
lisk = "https://rpc.api.lisk.com"

[etherscan]
lisk_sepolia = { key = "${API_KEY_BLOCKSCOUT}", url = "https://sepolia-blockscout.lisk.com/api" }
lisk = { key = "${API_KEY_BLOCKSCOUT}", url = "https://blockscout.lisk.com/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config